/* Generated by Together */

package impl.miw.business.usermanager;


import org.springframework.beans.factory.annotation.Autowired;

import com.miw.business.UserManagerService;
import com.miw.model.User;
import com.miw.persistence.UserDataService;

public class UserManager implements UserManagerService {

	@Autowired
	private UserDataService userDataService;
	

	public void setUserDataService(UserDataService userDataService) {
		this.userDataService = userDataService;
	}

	@Override
	public boolean isUser(User user) throws Exception {
		// TODO Auto-generated method stub
		return false;
	}
	
	public User newUser(User user) throws Exception {
		// TODO Auto-generated method stub
		return this.userDataService.newUser(user);
	}
}
